adapter: llava_next
name: LLaVA-Video-7B-Qwen2
model_path: lmms-lab/LLaVA-Video-7B-Qwen2
model_name: llava_qwen
conv_template: qwen_1_5
media: videos
torch_dtype: bfloat16
max_new_tokens: 32
eval:
  num_frames: 32
  max_frames: 64
